### ISSUE TITLE
Required parameter channelType not required in typing information

### ISSUE THREAD

**Issue by dyladan** [Dynatrace/OneAgent-SDK-for-NodeJs#1]
When making an outgoing remote call, the sdk fails if a channelType is left off, but it is claimed to be optional in the typing information.

**Comment by Flarna** [comment]
Yes, that's true. SDK requires that one of following properties is set in `ConnectionInfo`, `host`, `socketPath`,  `pipeName` or `channelType`.
I have to think about how I can improve this, not sure if typescript allows such a specification at all. Hints welcome!

**Comment by dyladan** [comment]
@Flarna Typescript does allow for something like this if you use union types. Something like this:

```typescript
export type ConnectionInfo = HostPortConnectionInfo | SocketPathConnectionInfo | PipeConnectionInfo | ChannelConnectionInfo;

export interface HostPortConnectionInfo {
  host: string;
  port?: string;
}

export interface SocketPathConnectionInfo {
  socketPath: string;
}

export interface PipeConnectionInfo {
  pipeName: string;
}

export interface ChannelConnectionInfo {
  channelType: ChannelType;
}
```

**Comment by Flarna** [comment]
I tried that yesterday (with some small changes as you can't create an interface extending from an union type) but it seems to be just have of the truth as it allows to set e.g. `host` and `socketPath` but it should be just one of them.
But it's definitely a step forward as it requires at least one.

**Comment by dyladan** [comment]
A I see the problem. Perhaps a discriminated union?

```typescript
export enum ConnectionType {
  Host,
  SocketPath,
  Pipe,
  Channel
}

export type ConnectionInfo =
  | HostPortConnectionInfo
  | SocketPathConnectionInfo
  | PipeConnectionInfo
  | ChannelConnectionInfo;

export type HostPortConnectionInfo = {
  type: ConnectionType.Host;
  host: string;
  port: string;
}

export type SocketPathConnectionInfo = {
  type: ConnectionType.SocketPath;
  socketPath: string;
}

export type PipeConnectionInfo = {
  type: ConnectionType.Pipe;
  pipeName: string;
}

export type ChannelConnectionInfo = {
  type: ConnectionType.Channel;
  channelType: ChannelType;
}

const opts: ConnectionInfo = {
  type: ConnectionType.Pipe,
  pipeName: "pipe name here"
}
```

**Comment by Flarna** [comment]
I wanted to avoid a discriminated union as user has to set an extra field `type`which is unneeded. if you look into other JS APIs with a similar need (e.g. redis,.. ) something like this is also not done. One target here was to act like others do.
Honestly speaking I have the feeling that typescript should improve the type checking for union types here. I think I will put this together in a small sample and report in the typescript repo.

**Comment by Flarna** [comment]
maybe related: https://github.com/Microsoft/TypeScript/issues/20863

**Comment by Flarna** [comment]
@dyladan I created PR #2 would be nice if you can take a look.

**Comment by Flarna** [comment]
> Honestly speaking I have the feeling that typescript should improve the type checking for union types here.

Seems this happened with typescript 3.3 :clap: :clap: :clap:
