### ISSUE TITLE
Custom Alerts in NodeJS application

### ISSUE THREAD

**Issue by MariaClemence** [Dynatrace/OneAgent-SDK-for-NodeJs#11]
Hello, 

I have application developed in NodeJS and deployed on cloud foundry. I need to raise custom alerts from NodeJS application to dynatrace similar to JMS feature in JAVA.

Use cases for custom alert generation is very application specific, example
 1. synchronization error.
 2. data purging failed. 

What are the possible ways to raise custom alerts from NodeJS application?

Thanks and Regards,
Vanessa

**Comment by Flarna** [comment]
@dtPaTh

**Comment by redheadtom** [comment]
Hi,

you can already use the OneAgent SDK for Node.js to set [custom request attributes](https://github.com/Dynatrace/OneAgent-SDK-for-NodeJs#set-custom-request-attributes). 

This request attributes can then be [used in Dynatrace](https://www.dynatrace.com/support/help/how-to-use-dynatrace/transactions-and-services/basic-concepts/request-attributes/) in a very flexible way, like to run ad-hoc analysis, use them to [customize the error detection](https://www.dynatrace.com/support/help/how-to-use-dynatrace/transactions-and-services/configuration/configure-service-error-detection/#detection-of-business-logic-related-errors-using-request-attributes) or to create metrics based on them (on which you can also define alerts). 

Best regards,

Thomas
