### ISSUE TITLE
Custom Metrics

### ISSUE THREAD

**Issue by PatrikSteuer** [Dynatrace/OneAgent-SDK-for-NodeJs#13]
I learned that the mentioned approach for custom metrics is not the way to go. Custom metrics should be exposed to Dynatrace using the [OpenTelemetry integration](https://www.dynatrace.com/news/blog/announcing-enterprise-grade-observability-at-scale-for-your-opentelemetry-custom-metrics-part-2/) in future. 

It would be helpful to adopt the documentation accordingly.

**Comment by z1c0** [comment]
Hi @PatrikSteuer,
there will be a documentation update and the existing metrics APIs will be marked deprecated then.
