### ISSUE TITLE
Missing Custom services

### ISSUE THREAD

**Issue by zelongc** [Dynatrace/OneAgent-SDK-for-NodeJs#21]
hello, is customServiceTracer a missing feature?
I am trying to trace a custom service, such as use a tracer to wrap a function (a graphql resolver).
It seems that customServiceTracer is availble for both java and python SDK however missing from nodejs sdk

**Comment by z1c0** [comment]
Hi,
correct, this feature was not implemented for the Node.js SDK.
I'll bring your use case up with PM.
Out of curiosity: Did you consider using OpenTelemetry SDK (there is OneAgent Node.js support for that)?

**Comment by zelongc** [comment]
@z1c0  Hey I didn't know about it, looks like it can report to dynatrace..I"ll have a look. 

* regarding bring it to PM: I believe there's a lot of case where ppl are using nodeJs to run up a Graphql server.. end of day all the traffic is in/out through one single REST endpoint, where is kinda off the radar of dynatrace monitoring.. unless the customer do something such as creating our own trace logic...

Thanks for the quick response!

**Comment by Flarna** [comment]
I will close this issue. Feel free to reopen if needed.
