### ISSUE TITLE
Custom Metrics

### ISSUE THREAD

**Issue by PatrikSteuer** [Dynatrace/OneAgent-SDK-for-NodeJs#3]
What is the best way to provide custom metrics from within a nodejs application. 

Providing a function within the sdk would reduce the need for rest calls and reduce complexity of deployments. Are there any other possibilities?

**Comment by SonjaChevre** [comment]
To understand the use case better, what kind of metrics do you want to report to Dynatrace?

Custom metrics is on our roadmap [1] for the SDK. In the meantime, you can either call the REST API or have a look at custom request attributes [2] to see if this could fit your use case. 

[1]: https://answers.dynatrace.com/spaces/483/dynatrace-product-ideas/idea/198106/planned-features-for-oneagent-sdk.html
[2]: https://www.dynatrace.com/news/blog/capture-any-request-attributes-using-oneagent-sdk/

**Comment by PatrikSteuer** [comment]
We have plenty of usecases and many teams are requesting for JMX like features in dynatrace. Currently they have to implement rest calls, as mentioned by you. This can be dangerous for the cluster, since it can be easily overwhelmed by these calls. 

So some usecases are:
 * Integration to libraries, e.g. DBAccess (Hana, rabbitMq, redis) for client side reporting
 * Number of used connections
 * Alerting based on thresholds

**Comment by SonjaChevre** [comment]
thanks for the details and sorry for the late answer, I have missed the notification. The use case you describe is totally in sync with what we want to achieve. 

As mentioned earlier this is on the roadmap (you can follow it there: https://answers.dynatrace.com/spaces/483/dynatrace-product-ideas/idea/198106/planned-features-for-oneagent-sdk.html) but not available at the moment.

**Comment by Moeriki** [comment]
Is there an ETA for the tracing of custom services?

**Comment by SonjaChevre** [comment]
Hi @Moeriki - are you interested in custom metrics or custom services? and what is your use case?

Note that you are commenting on closed issue, please consider creating a new issue for your questions.
Sonja
