### ISSUE TITLE
This package looks unmaintained, it hasn't been updated in 1 year, 7 months and 22 days. Consider looking for an alternative.

### ISSUE THREAD

**Issue by locochen** [Dynatrace/OneAgent-SDK-for-NodeJs#33]
When using the "@dynatrace/oneagent-sdk": "^1.5.0",  we got an warning that shows This package looks unmaintained, it hasn't been updated in 1 year, 7 months and 22 days. Consider looking for an alternative.

There is any plan to update or release a new version?

**Comment by dygabo** [comment]
`@dynatrace/oneagent-sdk`  has a stable API and there was no need to update this package after the introduction of trace context support last year. It has no depndencies to other packages either.
