### ISSUE TITLE
Custom service tracing

### ISSUE THREAD

**Issue by Moeriki** [Dynatrace/OneAgent-SDK-for-NodeJs#5]
Continuation of https://github.com/Dynatrace/OneAgent-SDK-for-NodeJs/issues/3#issuecomment-504948423.

Our use case is tracing specific parts of our code.

Right now we using the API to do this.

```js
httpClient.post('https://********.live.dynatrace.com/api/v1/events', {
  body: {
    eventType: 'CUSTOM_INFO',
    start: startTime,
    end: endTime,
    attachRules: { entityIds: [OUR_APPLICATION_ID] },
  }
});
```

I'd be nice to have this in the Agent API. I think it is on the roadmap… if so, is there an ETA?

Sincerely,

**Comment by SonjaChevre** [comment]
hi! first of all - very sorry about the delay. 

Unfortunately the API call you are using hasn't been designed for tracking code internals. It has been built for sending external event (new deployment, restart, ...): https://www.dynatrace.com/support/help/extend-dynatrace/dynatrace-api/environment-api/events/post-event/

We have in other languages a custom service concept (https://www.dynatrace.com/support/help/how-to-use-dynatrace/services-and-transactions/configuration/define-custom-services) but unfortunately not for node.js yet. This is not on the short term roadmap at the moment.

Sonja

**Comment by Moeriki** [comment]
Ok thanks for the feedback.
