### ISSUE TITLE
traceIncomingMessage throw invalid vendorName error 

### ISSUE THREAD

**Issue by LakhsmiC** [Dynatrace/OneAgent-SDK-for-NodeJs#7]
Hello Team 
we are facing the below issue even after giving a valid name in the vendorName. 
"SDK error:traceIncomingMessage: startData.vendorName is invalid",

We tried with both custom name and MessageSystemVendor.KAFKA  . 
We are not seeing the vendorName invalid error on the traceOutgoingMessage.

Please let me know if you need more information.

**Comment by z1c0** [comment]
Hi @LakhsmiC 

it looks like, there is already an open support ticket for this issue https://support.dynatrace.com/supportportal/browse/SUP-32380

It probably makes more sense to continue the discussion on this ticket.

**Comment by Flarna** [comment]
Seems your code is not correct: `startData = { dynatraceTag: ..., systemInfo };`

`vendorData` should be a property on `startData` not inside `systemInfo`.

You could use `Object.assign({ dynatraceTag: ... }, systemInfo)` or mutate `systemInfo`.

**Comment by Flarna** [comment]
According to the SUP ticket problem was solved.

**Comment by LakhsmiC** [comment]
Hello Gerhard

Yes , thankyou for your support .

Lakshmi
